# Generated by Django 5.1.6 on 2025-02-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_code',
            field=models.TextField(),
        ),
    ]
