# Generated by Django 5.1.6 on 2025-02-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='segment_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='segment_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.segment'),
        ),
    ]
